version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - apt update -y
      - apt-get install -y python3-venv
      - python3.6 -m venv test_venv
      - . test_venv/bin/activate
      - pip install --upgrade pip
      - pip install .
      - pip install -r tests/requirements.txt
      - rm -rf dspt
      - mkdir test-reports
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python test_app.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - web.py
    - appspec.yml
    - templates/layout.html
    - templates/test.html
    - scripts/mkdir.sh
    - scripts/start_flask.sh
    - scripts/stop_flask1.sh
    - scripts/stop_flask.py
